name: Docker Image CI

on:
  schedule:
  - cron: "20 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: spigot-builder
      BUILDTOOLS_BUILD: 110
      BUILDTOOLS_SHA1SUM: a6ef99c422578158b12239e5a2654314dd82aa4c
    strategy:
      matrix:
        BUILD_VERSION: [1.15, 1.15.1, 1.15.2]

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build \
            --build-arg BUILD_AUTHORS="Kane 'kawaii' Valentine <kane@cute.im>" \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg BUILDTOOLS_BUILD=$BUILDTOOLS_BUILD \
            --build-arg BUILDTOOLS_SHA1SUM=$BUILDTOOLS_SHA1SUM \
            --build-arg BUILD_VERSION=${{ matrix.BUILD_VERSION }} \
            --tag kawaii/spigot-builder:${{ matrix.BUILD_VERSION }} \
          $PWD
      - name: Authenticate to GitHub package registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Push the Docker image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          docker push $IMAGE_ID:${{ matrix.BUILD_VERSION }}
